{% set name = "benchling-sdk" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dbca7766bdcd8da298a2f90f1fe376c324194d99c72a26dfea599f03c29025ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry >=1.2
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - backoff >=1.10.0,<2.0.0
    - dataclasses-json >=0.5.2,<0.6.0
    - httpx >=0.23.0
    - attrs >=20.1.0,<23
    - python-dateutil >=2.8.0,<3.0.0
    - pyyaml >=6.0.0,<7.0.0
    - psutil >=5.9.4,<6.0.0
    - jwcrypto >=1.5.1,<2.0.0
    - benchling-api-client 2.0.287
    - certifi >=2022.12.7
    - ordered-set >=4.1.0,<5.0.0
  run_constrained:
    - cryptography >=42.0.0
    - python-jose >=3.3.0,<4.0.0

test:
  imports:
    - benchling_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/benchling-sdk/
  summary: SDK for interacting with the Benchling Platform.
  license: Apache-2.0
  license_file: LICENSE
extra:
  recipe-maintainers:
    - asford
    - PertuyF
    - jfolleas1
